# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 30) do

  create_table "bulletin_layouts", :force => true do |t|
    t.column "bulletin_id",  :integer,                 :default => 0,  :null => false
    t.column "name",         :string,    :limit => 30, :default => "", :null => false
    t.column "filetype",     :string,    :limit => 20, :default => "", :null => false
    t.column "charset",      :string,    :limit => 20, :default => "", :null => false
    t.column "rendered",     :text,                    :default => "", :null => false
    t.column "date_updated", :timestamp,                               :null => false
  end

  add_index "bulletin_layouts", ["bulletin_id", "name"], :name => "bulletin_id", :unique => true

  create_table "bulletins", :force => true do |t|
    t.column "project_id",    :integer,                :default => 0,   :null => false
    t.column "templet_id",    :integer,                :default => 0,   :null => false
    t.column "title",         :string,                 :default => "",  :null => false
    t.column "subject",       :string
    t.column "notes",         :text
    t.column "rendered",      :text
    t.column "status",        :string,    :limit => 1, :default => "O", :null => false
    t.column "date_released", :datetime
    t.column "updated_on",    :timestamp,                               :null => false
    t.column "filter_raw",    :text
    t.column "date",          :date
  end

  create_table "content_page_tags", :id => false, :force => true do |t|
    t.column "content_page_id", :integer, :null => false
    t.column "tag_id",          :integer, :null => false
  end

  create_table "content_pages", :force => true do |t|
    t.column "templet_id",  :integer,                                :null => false
    t.column "name",        :string,                :default => "",  :null => false
    t.column "status",      :string,   :limit => 1, :default => "O", :null => false
    t.column "abstract",    :text
    t.column "content",     :text
    t.column "notes",       :text
    t.column "created_on",  :datetime,                               :null => false
    t.column "updated_on",  :datetime,                               :null => false
    t.column "media_url",   :string
    t.column "bulletin_id", :integer,                                :null => false
  end

  create_table "email_templets", :force => true do |t|
    t.column "project_id",   :integer,                :default => 0,  :null => false
    t.column "templet_id",   :integer,                :default => 0,  :null => false
    t.column "type",         :string,    :limit => 1, :default => "", :null => false
    t.column "subject",      :string,                 :default => "", :null => false
    t.column "description",  :text
    t.column "date_created", :datetime,                               :null => false
    t.column "date_updated", :timestamp,                              :null => false
  end

  create_table "entries", :force => true do |t|
    t.column "section_id",   :integer,                 :default => 0,  :null => false
    t.column "title",        :text,                    :default => "", :null => false
    t.column "subtitle",     :text
    t.column "style",        :string,    :limit => 50
    t.column "body",         :text
    t.column "image_link",   :string
    t.column "image_text",   :text
    t.column "link",         :string
    t.column "link_text",    :string
    t.column "position",     :integer,   :limit => 6,  :default => 0,  :null => false
    t.column "date_created", :datetime,                                :null => false
    t.column "date_updated", :timestamp,                               :null => false
  end

  create_table "project_groups", :force => true do |t|
    t.column "name",       :string,   :default => "", :null => false
    t.column "created_on", :datetime
  end

  create_table "projects", :force => true do |t|
    t.column "name",              :string,    :limit => 50,  :default => "", :null => false
    t.column "sender",            :string,    :limit => 100, :default => "", :null => false
    t.column "report_recipients", :text
    t.column "domain",            :string
    t.column "description",       :text
    t.column "default_lang",      :string,    :limit => 3,   :default => "", :null => false
    t.column "date_updated",      :timestamp,                                :null => false
    t.column "project_group_id",  :integer,                  :default => 1
  end

  create_table "recipient_email_receipts", :id => false, :force => true do |t|
    t.column "bulletin_id",  :integer,               :default => 0, :null => false
    t.column "recipient_id", :integer,               :default => 0, :null => false
    t.column "status",       :string,   :limit => 1
    t.column "received",     :datetime
  end

  add_index "recipient_email_receipts", ["bulletin_id", "recipient_id"], :name => "bulletin_id"

  create_table "recipient_receipts", :force => true do |t|
    t.column "bulletin_id",  :integer,               :default => 0, :null => false
    t.column "recipient_id", :integer,               :default => 0, :null => false
    t.column "status",       :string,   :limit => 1
    t.column "received",     :datetime
    t.column "read",         :datetime
    t.column "hits",         :integer,               :default => 0, :null => false
  end

  add_index "recipient_receipts", ["bulletin_id", "recipient_id"], :name => "bulletin_id"

  create_table "recipients", :force => true do |t|
    t.column "email",            :string,                   :default => "",    :null => false
    t.column "firstname",        :string,    :limit => 128
    t.column "surname",          :string,    :limit => 64
    t.column "surname2",         :string,    :limit => 64
    t.column "lang_pref",        :string,    :limit => 3,   :default => "ES",  :null => false
    t.column "country",          :string
    t.column "mobile",           :string,    :limit => 64
    t.column "mobile_operator",  :string
    t.column "address",          :string
    t.column "city",             :string
    t.column "postcode",         :string,    :limit => 20
    t.column "created_on",       :datetime
    t.column "updated_on",       :timestamp,                                   :null => false
    t.column "new_data",         :text
    t.column "project_group_id", :integer,                  :default => 1
    t.column "confirmed_real",   :boolean,                  :default => false
  end

  create_table "sections", :force => true do |t|
    t.column "bulletin_id",  :integer,                 :default => 0,  :null => false
    t.column "name",         :string,                  :default => "", :null => false
    t.column "title",        :text
    t.column "style",        :string,    :limit => 50
    t.column "description",  :text
    t.column "type",         :string,    :limit => 10
    t.column "link",         :string
    t.column "link_text",    :string
    t.column "date_created", :datetime,                                :null => false
    t.column "date_updated", :timestamp,                               :null => false
  end

  create_table "subscriptions", :force => true do |t|
    t.column "recipient_id", :integer,               :default => 0, :null => false
    t.column "project_id",   :integer,               :default => 0, :null => false
    t.column "state",        :string,   :limit => 1
    t.column "confirm_code", :string
    t.column "created_on",   :datetime
    t.column "updated_on",   :datetime
  end

  add_index "subscriptions", ["recipient_id", "project_id"], :name => "recipient_project_id"

  create_table "tags", :force => true do |t|
    t.column "name",       :string
    t.column "created_on", :datetime
  end

  create_table "templet_layouts", :force => true do |t|
    t.column "templet_id",  :integer,                 :default => 0,             :null => false
    t.column "name",        :string,    :limit => 30, :default => "",            :null => false
    t.column "filetype",    :string,    :limit => 20, :default => "text/html",   :null => false
    t.column "charset",     :string,    :limit => 20, :default => "ISO-8859-15", :null => false
    t.column "edit_as_raw", :boolean,                 :default => false,         :null => false
    t.column "data",        :text,                    :default => "",            :null => false
    t.column "created_on",  :datetime
    t.column "updated_on",  :timestamp,                                          :null => false
    t.column "filter",      :string,    :limit => 20
  end

  create_table "templets", :force => true do |t|
    t.column "project_id",  :integer,                 :default => 0,     :null => false
    t.column "type",        :string,    :limit => 24
    t.column "type_code",   :string,    :limit => 1,  :default => "B",   :null => false
    t.column "name",        :string,    :limit => 50, :default => "",    :null => false
    t.column "subject",     :string
    t.column "static",      :boolean,                 :default => false, :null => false
    t.column "description", :text,                    :default => "",    :null => false
    t.column "created_on",  :datetime
    t.column "updated_on",  :timestamp,                                  :null => false
  end

  create_table "user_roles", :force => true do |t|
    t.column "user_id",         :integer,                      :null => false
    t.column "project_id",      :integer,                      :null => false
    t.column "edit_project",    :boolean,   :default => false, :null => false
    t.column "create_bulletin", :boolean,   :default => false, :null => false
    t.column "send_bulletin",   :boolean,   :default => false, :null => false
    t.column "edit_bulletin",   :boolean,   :default => false, :null => false
    t.column "edit_recipients", :boolean,   :default => false, :null => false
    t.column "edit_section",    :boolean,   :default => false, :null => false
    t.column "edit_entry",      :boolean,   :default => false, :null => false
    t.column "edit_templates",  :boolean,   :default => false, :null => false
    t.column "created_on",      :datetime,                     :null => false
    t.column "updated_on",      :timestamp,                    :null => false
    t.column "edit_pages",      :boolean,   :default => false, :null => false
    t.column "edit_files",      :boolean,   :default => false, :null => false
  end

  create_table "users", :force => true do |t|
    t.column "name",          :string,    :limit => 30, :default => "",    :null => false
    t.column "password_hash", :string,    :limit => 50, :default => "",    :null => false
    t.column "description",   :text,                    :default => "",    :null => false
    t.column "admin_role",    :boolean,                 :default => false, :null => false
    t.column "date_created",  :datetime,                                   :null => false
    t.column "date_updated",  :timestamp,                                  :null => false
  end

end
